apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  tracing:
    type: Jaeger
    sampling: 510
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        ingress:
          enabled: true
    kiali:
      install:
        dashboard:
          enableGrafana: true
          enablePrometheus: true
          enableTracing: true
        service:
          ingress:
            enabled: true
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod
  version: v2.6
  mode: ClusterWide
